### ISSUE TITLE
Suppression not always working when ProtectZeros = FALSE

### ISSUE THREAD

**Issue by JulieHawkins** [statisticsnorway/easySdcTable#1]
I feel like there is an error when protectZeros = FALSE.

I cannot figure out how to upload a csv, sorry!
![data](https://user-images.githubusercontent.com/22153994/57876000-21c1ed80-77c9-11e9-88f3-bddf5779ac8a.png)

I ran ProtectTable() on the data, with the following variables pre-set:
maxN <- 5
suppressionVal <- "s"
results_SDC <- ProtectTable(data, dimVar = 1, freqVar = 2:6, protectZeros = FALSE,  
                              maxN = maxN, total = "Total", method = "SIMPLEHEURISTIC",
                              suppression = suppressionVal)

This is what I got:

![image](https://user-images.githubusercontent.com/22153994/57876150-7cf3e000-77c9-11e9-86f2-8989bed7c228.png)

Because zeros are allowed (i.e., not protected), I was able to determine some suppressed values. In Group_24, I see the Total is 112, yet the sum of the non-suppressed values is 110. I know that zeros are allowed, therefore, the two suppressed values are not zero. They must then both be 1. I feel that one other value in that row should have been secondarily suppressed.

**Comment by olangsrud** [comment]
I apologize for not answering earlier.  Unfortunately, I didn’t notice the issue before today. I am not used to have issues on my github. In fact, your issue is the first one.

The problem you describe is a known problem of so-called singletons. The underlying function in the package sdcTable has a parameter called detectSingletons. When the parameter is TRUE "a singleton-detection procedure be run before protecting the data". The defalue is, however, FALSE and ProtectTable in easySdcTable uses the same default as protectTable in sdcTable.

To change the procedure, you can either 

add the parameter "detectSingletons=TRUE"  in the function call  

or 

replace "SIMPLEHEURISTIC" with "SimpleSingle" (try ?PTwrap to see  explanation)

You may try this on your data. (Since your data is just an image I haven’t tried myself)

**Comment by JulieHawkins** [comment]
Thank you. I will try that next time.
